# Site settings
title: BioContainers Hackthon
email: biodocker@gmail.com
url: https://biocontainers.pro/workshops
description: "The “ELIXIR Software Deployment Group” is one of the six working groups of the ELIXIR tools platform. It has been recently formed to support bioinformatics software deployment efforts including packages and containers. At the moment this group is sustained by ELIXIR Nodes sharing a common interest to work together on a harmonised strategy. The activities of this group are extremely relevant to other two groups within ELIXIR Tools platforms: “Workflows & workbenches” and “Software development best practices” because it represents the starting point for the development of reproducible pipelines and workflows in bioinformatics.
              This group would like to accelerate and consolidate the Containers Platform as a Service, and the integration with other groups like Workflows & workbenches and Software tools (Bio.Tools). To do so we proposed to have a 2.5 days hackathon. In practice the hackathon will give us the opportunity to work on three different topics:
              Improve the current metadata and definitions for BioContainers and increase the number of containers in  Biocontainers.
              Integration of Biocontainers (https://biocontainers.pro/) and other initiatives Bioshadock (http://bioshadock.genouest.org/), BioConda.
              Connect better the containers registry (http://biocontainers.pro/registry) with Bio.tools and Workflow systems such as Galaxy and CWL.
              Define a strategy (Metadata) for “Training Containers”, design an infrastructure for hosting containers in ELIXIR and engage the training community to create containers for training purposes."
keywords: "BioContainers, Docker, rkt, Bioinformatics"
skills: "BioContainers, Docker, rkt, Bioinformatics"
meta_author: BioContainers Group

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: BioContainers Group

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/biocontainers
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/BioContainers
  - title: github
    url: http://github.com/BioContainers

# Postal address (add as many lines as necessary)
address:
  - line: 9-11 October 2017
  - line: Paris, France

# Credits content
credits: 'Freelancer is a template created using Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
